/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void test() {
        String[] array = new String[] { "aa", "bb" };
        assertFalse(false);

    }

}
